console.log('Hello world with HTML'.toUpperCase());
let a = 5;
let b = 6;
let c = 6.9;
let d = '5';
let e = Number(d);
let f = +d;
console.log('e value: ', e, 'type', typeof e);
console.log('f value: ', f, 'type', typeof f);
console.log(a === e, 'a: ', typeof a, 'd: ', typeof d);